### ISSUE TITLE
NixOS Flake build fails with a SyntaxError on catppuccin-vsc build

### ISSUE THREAD

**Issue by henriquekirchheck** [catppuccin/vscode#461]
NixOS Flake fails to build with the following error

```
Running phase: unpackPhase
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking source archive /nix/store/ykshcpjawlfxcg0swyan7ay1diiq9kx4-dcq2gmdxand5h2b98n3p1hnkwyj8hd6h-catppuccin-vsc-3.16.0
source root is dcq2gmdxand5h2b98n3p1hnkwyj8hd6h-catppuccin-vsc-3.16.0
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: configurePhase
@nix { "action": "setPhase", "phase": "configurePhase" }
➤ YN0000: · Yarn 4.5.1
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 0s 720ms
➤ YN0000: ┌ Post-resolution validation
➤ YN0002: │ @catppuccin/vsc-storybook@workspace:packages/catppuccin-vsc-storybook doesn't provide less (pd0879), requested by @storybook/addon-styling and other dependencies.
➤ YN0002: │ @catppuccin/vsc-storybook@workspace:packages/catppuccin-vsc-storybook doesn't provide postcss (pffc5c), requested by @storybook/addon-styling.
➤ YN0002: │ @catppuccin/vsc-storybook@workspace:packages/catppuccin-vsc-storybook doesn't provide react (pe9cdc), requested by @storybook/addon-styling and other dependencies.
➤ YN0002: │ @catppuccin/vsc-storybook@workspace:packages/catppuccin-vsc-storybook doesn't provide react-dom (pf21d1), requested by @storybook/addon-styling and other dependencies.
➤ YN0002: │ @catppuccin/vsc-storybook@workspace:packages/catppuccin-vsc-storybook doesn't provide webpack (p16d88), requested by @storybook/addon-styling.
➤ YN0086: │ Some peer dependencies are incorrectly met by your project; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0086: │ Some peer dependencies are incorrectly met by dependencies; run yarn explain peer-requirements for details.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 15s 535ms
➤ YN0000: ┌ Link step
➤ YN0005: │ keytar@npm:7.9.0 lists build scripts, but its build has been explicitly disabled through configuration.
➤ YN0007: │ esbuild@npm:0.19.12 must be built because it never has been before or the last one failed
➤ YN0007: │ @vscode/vsce-sign@npm:2.0.5 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.18.20 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.20.2 must be built because it never has been before or the last one failed
➤ YN0007: │ es5-ext@npm:0.10.64 must be built because it never has been before or the last one failed
➤ YN0007: │ @catppuccin/vscode-monorepo@workspace:. must be built because it never has been before or the last one failed
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT .git can't be found
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT > @catppuccin/vscode@3.16.0 prepack
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT > yarn core:build && yarn build
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT 
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT CLI Building entry: src/browser.ts, src/main.ts, src/hooks/generateThemes.ts
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT CLI Using tsconfig: tsconfig.json
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT CLI tsup v8.0.2
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT CLI Target: node16
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT CLI Cleaning output folder
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT CJS Build start
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR [warn] [33m▲ [43;33m[[43;30mWARNING[43;33m][0m [1m"import.meta" is not available with the "cjs" output format and will be empty[0m [empty-import-meta]
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR 
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR     src/hooks/constants.ts:6:33:
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR [37m      6 │     ? path.dirname(fileURLToPath([32mimport.meta[37m.url))
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR         ╵                                  [32m~~~~~~~~~~~[0m
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR 
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR   You need to set the output format to "esm" for "import.meta" to work correctly.
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR 
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR 
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT CJS dist/browser.cjs              741.00 B
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT CJS dist/hooks/generateThemes.cjs 93.17 KB
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT CJS dist/main.cjs                 95.70 KB
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT CJS ⚡️ Build success in 213ms
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT  INFO  Files included in the VSIX:
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT catppuccin-vsc-3.16.0.vsix
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT ├─ [Content_Types].xml 
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT ├─ extension.vsixmanifest 
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT └─ extension/
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT    ├─ LICENSE.txt [1.04 KB]
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT    ├─ changelog.md 
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT    ├─ icon.png [45.96 KB]
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT    ├─ package.json [5.92 KB]
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT    ├─ readme.md 
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT    ├─ dist/
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT    │  ├─ browser.cjs [0.72 KB]
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT    │  └─ main.cjs [95.7 KB]
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT    └─ themes/
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT       ├─ frappe.json [65.18 KB]
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT       ├─ latte.json [65.18 KB]
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT       ├─ macchiato.json [65.18 KB]
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT       └─ mocha.json [65.17 KB]
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT 
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT  DONE  Packaged: catppuccin-vsc-3.16.0.vsix (13 files, 122.96 KB)
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR (node:360) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR (Use `node --trace-warnings ...` to show where the warning was created)
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT CLI Building entry: src/index.ts, src/compile.ts
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT CLI Using tsconfig: tsconfig.json
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT CLI tsup v8.0.2
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT CLI Using tsup config: /build/dcq2gmdxand5h2b98n3p1hnkwyj8hd6h-catppuccin-vsc-3.16.0/packages/catppuccin-vscode/tsup.config.js
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT CLI Target: node16
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT CLI Cleaning output folder
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT ESM Build start
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT CJS Build start
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT ESM dist/index.js          255.30 KB
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT ESM dist/compile.js        71.00 B
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT ESM dist/chunk-NQU6RZYT.js 110.57 KB
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT ESM ⚡️ Build success in 207ms
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT CJS dist/index.cjs   366.92 KB
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT CJS dist/compile.cjs 111.61 KB
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT CJS ⚡️ Build success in 214ms
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT DTS Build start
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT DTS ⚡️ Build success in 19902ms
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT DTS dist/index.d.ts    114.87 KB
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT DTS dist/compile.d.ts  116.35 KB
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT DTS dist/index.d.cts   114.87 KB
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT DTS dist/compile.d.cts 116.35 KB
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR npm notice
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR npm notice package: @catppuccin/vscode@3.16.0
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR npm notice Tarball Contents
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR npm notice 1.1kB LICENSE
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR npm notice 2.8kB README.md
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR npm notice 113.2kB dist/chunk-NQU6RZYT.js
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR npm notice 114.3kB dist/compile.cjs
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR npm notice 119.1kB dist/compile.d.cts
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR npm notice 119.1kB dist/compile.d.ts
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR npm notice 71B dist/compile.js
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR npm notice 375.7kB dist/index.cjs
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR npm notice 117.6kB dist/index.d.cts
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR npm notice 117.6kB dist/index.d.ts
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR npm notice 261.4kB dist/index.js
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR npm notice 1.4kB package.json
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR npm notice 50.7kB themes/frappe.json
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR npm notice 50.7kB themes/latte.json
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR npm notice 50.7kB themes/macchiato.json
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR npm notice 50.7kB themes/mocha.json
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR npm notice Tarball Details
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR npm notice name: @catppuccin/vscode
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR npm notice version: 3.16.0
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR npm notice filename: catppuccin-vscode-3.16.0.tgz
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR npm notice package size: 213.7 kB
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR npm notice unpacked size: 1.5 MB
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR npm notice shasum: 958f5ddec718c27baf7acd49e363034090618680
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR npm notice integrity: sha512-jKeBrN+dOOLm3[...]38dYgIF0y8CDQ==
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR npm notice total files: 16
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR npm notice
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDOUT catppuccin-vscode-3.16.0.tgz
➤ YN0000: └ Completed in 1m 9s
➤ YN0000: · Done with warnings in 1m 26s
configurePhase completed in 1 minutes 35 seconds
Running phase: buildPhase
@nix { "action": "setPhase", "phase": "buildPhase" }
undefined:1


SyntaxError: /build/dcq2gmdxand5h2b98n3p1hnkwyj8hd6h-catppuccin-vsc-3.16.0/packages/catppuccin-vsc/package.json: Unexpected end of JSON input
    at parse (<anonymous>)
    at Module._extensions..json (node:internal/modules/cjs/loader:1566:39)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at JoyCon.recusivelyResolve (/build/dcq2gmdxand5h2b98n3p1hnkwyj8hd6h-catppuccin-vsc-3.16.0/node_modules/joycon/lib/index.js:78:22)
    at async loadTsupConfig (/build/dcq2gmdxand5h2b98n3p1hnkwyj8hd6h-catppuccin-vsc-3.16.0/node_modules/tsup/dist/chunk-7G76EW2R.js:39:22)
    at async build (/build/dcq2gmdxand5h2b98n3p1hnkwyj8hd6h-catppuccin-vsc-3.16.0/node_modules/tsup/dist/index.js:2646:51)
    at async <anonymous> (/build/dcq2gmdxand5h2b98n3p1hnkwyj8hd6h-catppuccin-vsc-3.16.0/packages/catppuccin-vsc/build.ts:15:1)

Node.js v20.18.0
```

Unfortunately, couldn't get yarn to work to try to build it manually and compare

**Comment by sgoudham** [comment]
Does https://github.com/catppuccin/vscode/commit/7b0ff73aa9e9718cbe418a3f90f771aa14a655b8 fix the build for you?

**Comment by JuneStepp** [comment]
Fixed it for me.

**Comment by sgoudham** [comment]
> Fixed it for me.

Thanks for confirming! I'll close this as resolved but feel free to re-open @henriquekirchheck if you're still running into issues.
