### ISSUE TITLE
Accent color with custom opacity in UI color overrides won't compile

### ISSUE THREAD

**Issue by laurinneff** [catppuccin/vscode#69]
If you set any color to something like `accent 0.5`, the theme won't recompile and this error message is printed to the console in devtools:

<details>
<summary>error message</summary>
<pre>
  ERR Cannot read properties of undefined (reading 'replace'): TypeError: Cannot read properties of undefined (reading 'replace')
    at n (c:\Users\lan\.vscode\extensions\catppuccin.catppuccin-vsc-2.3.0\dist\main.js:1:48532)
    at c:\Users\lan\.vscode\extensions\catppuccin.catppuccin-vsc-2.3.0\dist\main.js:1:49620
    at Array.map (<anonymous>)
    at V (c:\Users\lan\.vscode\extensions\catppuccin.catppuccin-vsc-2.3.0\dist\main.js:1:49535)
    at D (c:\Users\lan\.vscode\extensions\catppuccin.catppuccin-vsc-2.3.0\dist\main.js:1:64761)
    at F.<anonymous> (c:\Users\lan\.vscode\extensions\catppuccin.catppuccin-vsc-2.3.0\dist\main.js:1:65286)
    at Generator.next (<anonymous>)
    at c:\Users\lan\.vscode\extensions\catppuccin.catppuccin-vsc-2.3.0\dist\main.js:1:1083
    at new Promise (<anonymous>)
    at C (c:\Users\lan\.vscode\extensions\catppuccin.catppuccin-vsc-2.3.0\dist\main.js:1:903)
    at c:\Users\lan\.vscode\extensions\catppuccin.catppuccin-vsc-2.3.0\dist\main.js:1:65256
    at Array.map (<anonymous>)
    at F.<anonymous> (c:\Users\lan\.vscode\extensions\catppuccin.catppuccin-vsc-2.3.0\dist\main.js:1:65249)
    at Generator.next (<anonymous>)
    at c:\Users\lan\.vscode\extensions\catppuccin.catppuccin-vsc-2.3.0\dist\main.js:1:1083
    at new Promise (<anonymous>)
    at C (c:\Users\lan\.vscode\extensions\catppuccin.catppuccin-vsc-2.3.0\dist\main.js:1:903)
    at F.updateThemes (c:\Users\lan\.vscode\extensions\catppuccin.catppuccin-vsc-2.3.0\dist\main.js:1:65204)
    at c:\Users\lan\.vscode\extensions\catppuccin.catppuccin-vsc-2.3.0\dist\main.js:1:66396
    at p.invoke (c:\Users\lan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
    at v.deliver (c:\Users\lan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
    at b.fire (c:\Users\lan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
    at n.$acceptConfigurationChanged (c:\Users\lan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:101:26409)
    at c:\Users\lan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:101:25663
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
</pre>
</details>

Using an actual color or removing the opacity makes the theme compile again

**Comment by nekowinston** [comment]
Good catch! Didn't think to test that - I'll work on it later.
